### PR TITLE
Release tasks for CE 4.4.7

### PR DESCRIPTION
**Pull request by AMcFarlandCampbellR3**

### CODE REVIEW

**Review by erinking-r3 — DISMISSED** [review]
looks good to me

**Review by sachingokhale — COMMENTED** [review]
LGTM

**Review by nargas-ritu — DISMISSED** [review]
LGTM

**Review by dimosr — DISMISSED** [review]
LGTM

**Review by nargas-ritu — APPROVED** [review]
LGTM

**Comment by AMcFarlandCampbellR3** [comment]
I will merge and publish as soon as I get a tech writer to approve this. The other reviewers have either signed off in the comments or explicitly approved.

**Review by edward-prosser — APPROVED** [review]

**Pull request merged**
