### PR TITLE
DOC-1978 jchrisjones/fix/update-packages: All packages are at the latest

### PR DESCRIPTION
**Pull request by jchrisjones**
* Webpack.config.js was given a complete rewrite.

* images in scss files were converted to base64

* removed unused packages from package.json

### CODE REVIEW

**Review by barrylapthorn — APPROVED** [review]
LGTM, though I haven't had a chance to actually build this and check.

@ivanterziev-r3 - I'd suggest someone builds this or deploys it to one of your test servers. As I'm out for a couple of weeks.

**Comment by ivanterziev-r3** [comment]
Related to 453

**Comment by AMcFarlandCampbellR3** [comment]
I built this locally and on https://seel.corda.net/. Seems to work OK.

**Review by barrylapthorn — APPROVED** [review]
LGTM

**Review by ivanterziev-r3 — APPROVED** [review]
LGTM

**Pull request merged**
