### PR TITLE
DOC-363 & DOC-32

### PR DESCRIPTION
**Pull request by edward-prosser**

### CODE REVIEW

**Review by ivanterziev-r3 — DISMISSED** [review]
LGTM

**Comment by r3ltsupport** [comment]
Looks good. Thank you

**Review by r3ltsupport — COMMENTED** [review]
Looks good for DOC-32.  Thank you.

**Review by ivanterziev-r3 — APPROVED** [review]
LGTM

**Comment by ivanterziev-r3** [comment]
@edward-prosser Merging and publishing this - if you need to make additional changes please open a new PR.

**Pull request merged**
