### PR TITLE
DOC-2229: Corrected indentation in extraConfig section of notary configuration …

### PR DESCRIPTION
**Pull request by taylorharvey-r3**
…fields.

### CODE REVIEW

**Comment by ivanterziev-r3** [comment]
putting on hold as there's some discrepancy between the ops guide pages and the "main" node section pages

**Comment by rick-r3** [comment]
Yes, this is a correct interpretation of my ramblings on the support JIRA!

**Comment by ivanterziev-r3** [comment]
Thanks @rick-r3

**Review by relyafi — COMMENTED** [review]
Indentation looks good. I would add that it appears we are missing a `batchTimeoutMs` option, which behaves in the same way as in the mysql / jpa notary blocks (which define this setting too).

**Comment by taylorharvey-r3** [comment]
Thanks, @rick-r3 and @relyafi . Ramzi, I've added the option you mentioned. Can you review once more?

**Review by relyafi — APPROVED** [review]

**Review by ivanterziev-r3 — APPROVED** [review]
LGTM

**Pull request merged**
