### PR TITLE
EG-4015: document the maximum character limit across the X500 name

### PR DESCRIPTION
**Pull request by amosmwsmith**

### CODE REVIEW

**Comment by ivanterziev-r3** [comment]
Thanks @amosmwsmith. Can you also please propagate this change upstream to all `node-naming.md` files for OS 4.4-4.6 and also CE 4.0-4.6?

**Review by AMcFarlandCampbellR3 — DISMISSED** [review]
LGTM

**Comment by amosmwsmith** [comment]
thanks Ivan - have merged into relevant Enterprise versions but I noticed the Corda OS  versions above 4.3 already had equivalent comment added as follows "The maximum number of characters in the whole x500 name string is 128 characters"

**Comment by ivanterziev-r3** [comment]
Thanks @amosmwsmith - yes in this case we can consider this done, thanks!

**Review by ivanterziev-r3 — APPROVED** [review]
LGTM

**Pull request merged**
